name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Build production bundle
        run: npm run build

      - name: Archive production build
        run: tar -czf doomer-tune-machine_${GITHUB_REF_NAME}.tar.gz dist

      - name: Publish GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: doomer-tune-machine_${{ github.ref_name }}.tar.gz
          generate_release_notes: true
